version: "3"
services:
  app:
    container_name: a1nu-bot-app
    image: a1nu-bot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    env_file:
      - .env
    environment:
      - PROFILE=prod
    depends_on:
      - db
    links:
      - "db:database"
  db:
    image: "postgres:11"
    container_name: "bot-db"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: